spring.http.multipart.max-file-size: 6MB
spring.datasource.url: jdbc:h2:~/remote-sound;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: remote-sound
spring.datasource.password:
spring.jpa.hibernate.ddl-auto: validate
spring.datasource.initialize: false

sound:
  control:
    toggle-mute: $wshShell.SendKeys([char]173)
    min: 1..50 | % {$wshShell.SendKeys([char]174)}
    max: 1..50 | % {$wshShell.SendKeys([char]175)}
    down: $wshShell.SendKeys([char]174)
    up: $wshShell.SendKeys([char]175)

