spring.http.multipart.max-file-size: 6MB

sound:
  control:
    toggle-mute: $wshShell = new-object -com wscript.shell;$wshShell.SendKeys([char]173)
    min: $wshShell = new-object -com wscript.shell;1..50 | % {$wshShell.SendKeys([char]174)};
    max: $wshShell = new-object -com wscript.shell;1..50 | % {$wshShell.SendKeys([char]175)};
    down: $wshShell = new-object -com wscript.shell;$wshShell.SendKeys([char]174)
    up: $wshShell = new-object -com wscript.shell;$wshShell.SendKeys([char]175)
